import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<div className='bg-slate-100 p-2'>
      	<p className='text-xl font-bold'>Next Shop</p>
        <p className='text-sm'>HyeongUk Kang</p>
        <p> - TailwindCSS </p>
        <p> - MongoDB </p>
      </div>
    </div>
  )
}
